trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'MyAzureSubscription'  # Update with your Azure subscription name
  resourceGroup: 'static_website'
  storageAccountName: 'storage244'
  containerName: '$web'  # Default container for static websites
  indexPage: 'index.html'
  errorPage: '404.html'
  githubRepo: 'https://github.com/Waseema31/website1'  # Replace with your GitHub repo URL

stages:
  - stage: Deploy
    displayName: 'Deploy Static Website to Azure Storage'
    jobs:
      - job: DeployResources
        displayName: 'Deploy Azure Static Website Resources'
        steps:
          - task: Checkout@1
            inputs:
              repository: '$(githubRepo)'
              clean: true

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Enable Static Website Hosting on Existing Storage Account
                az storage blob service-properties update --account-name $(storageAccountName) --resource-group $(resourceGroup) --static-website --index-document $(indexPage) --error-document $(errorPage)

                # Upload Website Files to the '$web' container
                az storage blob upload-batch -d $(containerName) --account-name $(storageAccountName) --source $(System.DefaultWorkingDirectory)

                echo "Static website deployed successfully to Azure Storage."
